// ═══════════════════════════════════════════════════════════════════════════
//                           S H A D O W D A G
//                     © ShadowDAG Project — All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════
//
// Advanced Pruning Engine — Removes old blocks and UTXO data while
// maintaining chain validity through pruning proofs.
//
// Unlike basic pruning, this supports:
//   - Proof-based pruning (can verify chain without full history)
//   - UTXO commitment snapshots (Merkle root of UTXO set)
//   - Configurable pruning depth (blocks, time, or size)
//   - Archival mode (no pruning)
//   - Pruned-node sync (bootstrap from UTXO snapshot)
//
// Pruning levels:
//   - Full:     Keep everything (archival node)
//   - Standard: Keep last 3 days + UTXO commitments
//   - Minimal:  Keep last 24 hours + UTXO commitments
//   - Ultra:    Keep last 6 hours + compact UTXO set only
// ═══════════════════════════════════════════════════════════════════════════

use std::time::{SystemTime, UNIX_EPOCH};
use sha2::{Sha256, Digest};

/// Pruning depth profiles
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum PruningLevel {
    /// Keep all blocks forever (archival node)
    Full,
    /// Keep 3 days of blocks + commitments (259,200 blocks at 1 BPS)
    Standard,
    /// Keep 24 hours of blocks + commitments
    Minimal,
    /// Keep 6 hours + compact UTXO only (ultra-light)
    Ultra,
    /// Custom depth in seconds
    Custom(u64),
}

impl PruningLevel {
    /// Pruning depth in seconds
    pub fn depth_secs(&self) -> u64 {
        match self {
            PruningLevel::Full     => u64::MAX,
            PruningLevel::Standard => 3 * 86_400,    // 3 days
            PruningLevel::Minimal  => 86_400,          // 24 hours
            PruningLevel::Ultra    => 6 * 3_600,       // 6 hours
            PruningLevel::Custom(s)=> *s,
        }
    }

    /// Estimated storage per day at 1 BPS (MB)
    pub fn storage_per_day_mb(&self) -> f64 {
        match self {
            PruningLevel::Full     => f64::INFINITY,
            PruningLevel::Standard => 500.0 * 3.0,
            PruningLevel::Minimal  => 500.0,
            PruningLevel::Ultra    => 125.0,
            PruningLevel::Custom(s)=> 500.0 * (*s as f64 / 86_400.0),
        }
    }
}

/// UTXO commitment (Merkle root of the UTXO set at a specific height)
#[derive(Debug, Clone)]
pub struct UtxoCommitment {
    pub height:      u64,
    pub merkle_root: String,
    pub utxo_count:  u64,
    pub total_value: u64,
    pub timestamp:   u64,
}

impl UtxoCommitment {
    pub fn compute(height: u64, utxo_hashes: &[String], total_value: u64) -> Self {
        let merkle_root = Self::compute_merkle_root(utxo_hashes);
        Self {
            height,
            merkle_root,
            utxo_count: utxo_hashes.len() as u64,
            total_value,
            timestamp: now_secs(),
        }
    }

    fn compute_merkle_root(hashes: &[String]) -> String {
        if hashes.is_empty() {
            return "0".repeat(64);
        }

        let mut layer: Vec<Vec<u8>> = hashes.iter()
            .map(|h| hex::decode(h).unwrap_or_else(|_| h.as_bytes().to_vec()))
            .collect();

        while layer.len() > 1 {
            if layer.len() % 2 == 1 {
                layer.push(layer.last().cloned().unwrap_or_default());
            }
            layer = layer.chunks(2).map(|pair| {
                let mut h = Sha256::new();
                h.update(b"ShadowDAG_UTXO_Commit_v1");
                h.update(&pair[0]);
                h.update(&pair[1]);
                h.finalize().to_vec()
            }).collect();
        }

        hex::encode(&layer[0])
    }

    pub fn verify(&self, utxo_hashes: &[String]) -> bool {
        let computed = Self::compute_merkle_root(utxo_hashes);
        computed == self.merkle_root
    }
}

/// Pruning proof -- allows a node to verify chain validity without full history.
///
/// **WARNING (Bug #143 + #144):** There is a mismatch between `generate_proof()`
/// and `verify()`:
///   - `generate_proof()` builds `proof_chain` from UTXO hashes (not actual block
///     headers) and sets `blue_scores` to a single-element vec `[lowest_block]`.
///   - `verify()` checks that `blue_scores.len() == proof_chain.len()`, so proofs
///     generated by `generate_proof()` will almost always fail verification when
///     there are more than one UTXO hashes.
///   - `selected_chain` is also populated from UTXO hashes rather than from actual
///     selected-parent-chain block headers.
///
/// TODO(production): Replace the placeholder `generate_proof()` implementation with
/// real GHOSTDAG selected-parent-chain headers and corresponding blue scores so that
/// `verify()` can meaningfully validate the proof. The `verify()` logic itself is
/// structurally correct; only the proof *generation* side needs to be reworked.
#[derive(Debug, Clone)]
pub struct PruningProof {
    /// Height at which pruning was performed
    pub pruning_height:     u64,
    /// UTXO commitment at the pruning point
    pub utxo_commitment:    UtxoCommitment,
    /// Block hashes forming the proof chain
    pub proof_chain:        Vec<String>,
    /// GHOSTDAG blue scores for proof blocks
    pub blue_scores:        Vec<u64>,
    /// Selected parent chain from genesis to pruning point
    pub selected_chain:     Vec<String>,
}

impl PruningProof {
    /// Verify the pruning proof is valid
    pub fn verify(&self) -> bool {
        // 1. Proof chain must not be empty
        if self.proof_chain.is_empty() { return false; }

        // 2. Blue scores must match proof chain length
        if self.blue_scores.len() != self.proof_chain.len() { return false; }

        // 3. Blue scores must be monotonically increasing
        for window in self.blue_scores.windows(2) {
            if window[1] < window[0] { return false; }
        }

        // 4. Selected chain must not be empty
        if self.selected_chain.is_empty() { return false; }

        // 5. UTXO commitment must be at pruning height
        if self.utxo_commitment.height != self.pruning_height { return false; }

        true
    }
}

/// Pruning result statistics
#[derive(Debug, Clone)]
pub struct PruneResult {
    pub blocks_pruned:    u64,
    pub headers_kept:     u64,
    pub utxos_compacted:  u64,
    pub bytes_freed:      u64,
    pub duration_ms:      u128,
    pub new_lowest_block: u64,
}

/// Advanced Pruning Engine
pub struct AdvancedPruningEngine {
    level:        PruningLevel,
    commitments:  Vec<UtxoCommitment>,
    lowest_block: u64,
    total_pruned: u64,
}

impl AdvancedPruningEngine {
    pub fn new(level: PruningLevel) -> Self {
        Self {
            level,
            commitments: Vec::new(),
            lowest_block: 0,
            total_pruned: 0,
        }
    }

    /// Check if a block at given height should be pruned
    pub fn should_prune(&self, block_height: u64, current_height: u64, bps: u32) -> bool {
        if self.level == PruningLevel::Full { return false; }

        let depth_blocks = self.level.depth_secs() * bps as u64;
        current_height.saturating_sub(block_height) > depth_blocks
    }

    /// Calculate which blocks should be pruned
    pub fn select_blocks_to_prune(
        &self,
        current_height: u64,
        bps:            u32,
    ) -> (u64, u64) {
        if self.level == PruningLevel::Full { return (0, 0); }

        let keep_blocks = self.level.depth_secs() * bps as u64;
        let prune_below = current_height.saturating_sub(keep_blocks);

        if prune_below <= self.lowest_block { return (0, 0); }

        (self.lowest_block, prune_below)
    }

    /// Execute pruning and create UTXO commitment
    pub fn prune(
        &mut self,
        from_height:   u64,
        to_height:     u64,
        utxo_hashes:   &[String],
        total_value:   u64,
    ) -> PruneResult {
        let start = std::time::Instant::now();

        let blocks_to_prune = to_height.saturating_sub(from_height);

        // Create UTXO commitment at the new lowest point
        let commitment = UtxoCommitment::compute(to_height, utxo_hashes, total_value);
        self.commitments.push(commitment);

        // Keep only last 10 commitments
        if self.commitments.len() > 10 {
            self.commitments.remove(0);
        }

        self.lowest_block = to_height;
        self.total_pruned += blocks_to_prune;

        // Estimated bytes freed (avg 1KB per block)
        let bytes_freed = blocks_to_prune * 1024;

        PruneResult {
            blocks_pruned:    blocks_to_prune,
            headers_kept:     to_height, // We keep all headers
            utxos_compacted:  utxo_hashes.len() as u64,
            bytes_freed,
            duration_ms:      start.elapsed().as_millis(),
            new_lowest_block: to_height,
        }
    }

    /// Generate a pruning proof for the current state.
    ///
    /// **WARNING (Bug #143):** This is a placeholder implementation. `proof_chain`
    /// and `selected_chain` are populated from UTXO hashes, and `blue_scores` is a
    /// single-element vec. This causes `PruningProof::verify()` to fail when
    /// `proof_chain.len() != blue_scores.len()`. A production implementation must
    /// supply actual block headers and their GHOSTDAG blue scores.
    pub fn generate_proof(&self, utxo_hashes: &[String], total_value: u64) -> Option<PruningProof> {
        if self.lowest_block == 0 { return None; }

        let commitment = UtxoCommitment::compute(self.lowest_block, utxo_hashes, total_value);

        Some(PruningProof {
            pruning_height:  self.lowest_block,
            utxo_commitment: commitment,
            // Proof chain: hashes of blocks from pruning point to current tip
            // In production, this would be the selected parent chain headers
            proof_chain:     utxo_hashes.iter().take(10).cloned().collect(),
            blue_scores:     vec![self.lowest_block],
            selected_chain:  utxo_hashes.iter().take(5).cloned().collect(),
        })
    }

    /// Get current pruning level
    pub fn level(&self) -> PruningLevel { self.level }
    pub fn lowest_block(&self) -> u64 { self.lowest_block }
    pub fn total_pruned(&self) -> u64 { self.total_pruned }
    pub fn commitment_count(&self) -> usize { self.commitments.len() }

    pub fn latest_commitment(&self) -> Option<&UtxoCommitment> {
        self.commitments.last()
    }

    pub fn status(&self) -> String {
        format!(
            "Pruning: {:?} | Lowest: {} | Total pruned: {} | Commitments: {}",
            self.level, self.lowest_block, self.total_pruned, self.commitments.len()
        )
    }
}

fn now_secs() -> u64 {
    SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn full_level_never_prunes() {
        let engine = AdvancedPruningEngine::new(PruningLevel::Full);
        assert!(!engine.should_prune(0, 1_000_000, 1));
    }

    #[test]
    fn standard_prunes_old_blocks() {
        let engine = AdvancedPruningEngine::new(PruningLevel::Standard);
        let depth = 3 * 86_400; // 3 days in blocks at 1 BPS
        assert!(engine.should_prune(0, depth + 100, 1));
        assert!(!engine.should_prune(depth - 10, depth + 100, 1));
    }

    #[test]
    fn prune_updates_lowest_block() {
        let mut engine = AdvancedPruningEngine::new(PruningLevel::Minimal);
        let utxos = vec!["hash1".to_string(), "hash2".to_string()];
        let result = engine.prune(0, 1000, &utxos, 5000);

        assert_eq!(result.blocks_pruned, 1000);
        assert_eq!(engine.lowest_block(), 1000);
        assert_eq!(engine.commitment_count(), 1);
    }

    #[test]
    fn utxo_commitment_verification() {
        let hashes = vec![
            "aabb".to_string(),
            "ccdd".to_string(),
        ];
        let commitment = UtxoCommitment::compute(100, &hashes, 1000);
        assert!(commitment.verify(&hashes));
        assert!(!commitment.verify(&["wrong".to_string()]));
    }

    #[test]
    fn pruning_proof_validation() {
        let commitment = UtxoCommitment::compute(100, &["a".to_string()], 500);
        let proof = PruningProof {
            pruning_height: 100,
            utxo_commitment: commitment,
            proof_chain: vec!["block_a".to_string()],
            blue_scores: vec![100],
            selected_chain: vec!["genesis".to_string()],
        };
        assert!(proof.verify());
    }

    #[test]
    fn invalid_proof_detected() {
        let commitment = UtxoCommitment::compute(100, &["a".to_string()], 500);
        let bad_proof = PruningProof {
            pruning_height: 200, // Mismatch with commitment
            utxo_commitment: commitment,
            proof_chain: vec![],
            blue_scores: vec![],
            selected_chain: vec![],
        };
        assert!(!bad_proof.verify());
    }

    #[test]
    fn pruning_levels_storage_estimates() {
        assert!(PruningLevel::Standard.storage_per_day_mb() > PruningLevel::Ultra.storage_per_day_mb());
        assert!(PruningLevel::Full.depth_secs() == u64::MAX);
    }

    #[test]
    fn select_blocks_to_prune_range() {
        let engine = AdvancedPruningEngine::new(PruningLevel::Ultra);
        // Ultra = 6 hours = 21,600 blocks at 1 BPS
        let (_from, to) = engine.select_blocks_to_prune(100_000, 1);
        assert!(to > 0);
        assert!(to < 100_000);
    }
}
